add product list widget
DV-mentoring/ecommerce pull request #3
Opened 2024-12-09 15:23 UTC by Yockium

2024-12-09 16:53 UTC, Triton556 requested changes

2024-12-09 16:53 UTC, Triton556 commented on src/entities/Product/model/api.ts
> +
что такое entities/../model? это не похоже на FSD, больше на какой-то из мобильных mvc\mvvm

2024-12-09 16:53 UTC, Triton556 commented on src/widgets/ProductList/ui/ProductList.tsx
> +    const loadInitialProducts = async () => {
эта и функция ниже - одно и то же, у них почти вся логика та же самая. удали фнукцию инишиал продактс, используй просто fetchProducts и сделай просто состояние текущей страницы, при нажатии на кнопку состояние += 1, а в юз эффект просто добавь в массив зависимостей этот стейт

2024-12-09 16:53 UTC, Triton556 commented on src/widgets/ProductList/ui/ProductList.tsx
> +            {products.length > 0 ? (
не привязывайся в тернарнике к длинне массива, если у тебя будет ошибка в запросе, какое состояние будет тут в компоненте, или если пришёл пустой массив товаров? Судя по коду - будет состояние загрузки
Сделай стейт для ошибки и если ошибка выводи её, а уже потом тернарник зависящий от состояния загрузки а не колличества элементов в массиве

2024-12-09 16:53 UTC, Triton556 commented on src/widgets/ProductList/ui/ProductList.tsx
> +            console.log("Current unique product ids --->", productIds.current);
перед отправкой ПРа либо удаляй логи, либо пиши зачем они нужны тебе)

2024-12-09 16:53 UTC, Triton556 commented on src/entities/Product/model/api.ts
> +        console.log("gavno", response.data.data);
тоже убрать надо логи перед отправкой ПРа))

2024-12-09 16:53 UTC, Triton556 commented on src/entities/Product/ui/ProductCard.tsx
> +export default ProductCard;
Используй именованные экспорты вместо дефолтных

2024-12-10 17:25 UTC, Yockium commented on src/entities/Product/model/api.ts
> +
в модел добавляю бизнес логику, погуглил структуру FSD, там использовали model, но это тоже не обязательный критерий, просто там где я смотрел делали так

2024-12-11 03:59 UTC, Triton556 requested changes
В целом всё отлично, только 1 момент с isFetching. И не понимаю что с айдишникаси делаешь и зачем нужен hasMore

2024-12-11 03:59 UTC, Triton556 commented on src/widgets/ProductList/ui/ProductList.tsx
> +                setHasMore(false);
А что за логика с has more и проверкой айдишников?

2024-12-11 03:59 UTC, Triton556 commented on src/widgets/ProductList/ui/ProductList.tsx
> +    const isFetching = useRef(false);
Отписал в комменте в notion

2024-12-11 03:59 UTC, Triton556 commented on src/widgets/ProductList/ui/ProductList.tsx
> +            if (uniqueProducts.length < 8){
Тут 8 это так называемое магическое число, непонятно что оно означает и откуда взялось, лучше вынести в константы

2024-12-12 03:56 UTC, Triton556 requested changes

2024-12-12 03:56 UTC, Triton556 commented on src/widgets/ProductList/ui/ProductList.tsx
> +                    disabled={loading || isInitialLoading}
А что за isInitialLoading?

2024-12-12 03:56 UTC, Triton556 commented on src/widgets/ProductList/ui/ProductList.tsx
> +    const loadProducts = async() => {
Снова магическое число и ниже в этом же клмпоненте

2024-12-12 16:55 UTC, Yockium commented on src/widgets/ProductList/ui/ProductList.tsx
> +                setHasMore(false);
uniqueProducts это проверка на возможное дублирование товаров, у меня бывало что там ломается у апи, я вот таким образом проверял чтобы убедиться. Set ProductIds содержит все уникальные id товаров отображенных в UI, для логики дополнительной проверки на клиентской стороне, даже если апи идеально настроен. Слышал, что лучше на клиенте убедиться, чем пологаться на апи.

hasMore это проверка на оставшееся количество товаров у эндпоинта. Если последняя порция товаров имела меньше уникальных товаров чем 8 (выведу в константу), значит флаг hasMore становится false, кнопка load more больше не отображается.

Получается если что то пошло не так у апи, произошло дублирование какое либо, то пользователь просто получит последнюю порцию товаров (и она будет меньше чем константа 8, либо иная другая, просто у меня всего 12 товаров пока что), даже если это был единичный случай и только один или несколько товаров пришли с дубликатами. Пока не знаю как это можно по другому сделать, возможно после такого сценария сделать логику с тестовый запросом следующей страницы сделать. И если все таки прийдут новые уникальные товары, то можно будет продолжить логику загрузки с load more.

2024-12-12 17:04 UTC, Yockium commented on src/widgets/ProductList/ui/ProductList.tsx
> +            if (uniqueProducts.length < 8){
вывел это в константу, productSet. Пока будет 8 ибо у меня всего 12 товаров добавленно. Надо будет проверить как кнопка будет отрабатывать если товаров больше чем 16, чтобы кнопку load more можно было больше чем 1 раз нажать, но по сути не должно ломаться.

2024-12-12 17:21 UTC, Yockium commented on src/widgets/ProductList/ui/ProductList.tsx
> +            {products.length > 0 ? (
Привязал к isInitialLoading, чтобы массив с нуля мапился один раз при монтировании компонента, а дальше продукты подгружались в конец, ниже описал это решение.

2024-12-13 15:53 UTC, Triton556 requested changes

2024-12-13 17:07 UTC, Yockium commented on src/widgets/ProductList/ui/ProductList.tsx
> +    const productSet = 8;
Точно, забыл про это

2024-12-13 17:10 UTC, Yockium commented on src/widgets/ProductList/ui/ProductList.tsx
> +                    <ProductCard
Деструктуризировал product и получил total продуктов из запроса. Теперь hasMore зависит от него.

2024-12-17 08:13 UTC, Triton556 approved these changes

2024-12-17 17:16 UTC, merged